import type {Metadata} from "next";
import {DynaPuff, Funnel_Sans} from "next/font/google";
import "./globals.css";
import FooterComponent from "@/components/ui/footer";

const sans = DynaPuff({
    variable: "--font-sans",
    subsets: ["latin"],
});

const mono = Funnel_Sans({
    variable: "--font-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${sans.variable} ${mono.variable} antialiased min-h-screen`}
            >
                <div className="flex flex-col justify-start min-h-screen">
                    <div>{children}</div>
                    <div className="flex flex-col justify-end flex-1">
                        <FooterComponent />
                    </div>
                </div>
            </body>
        </html>
    );
}
