import type { Metadata } from "next";
import { DynaPuff, Funnel_Sans } from "next/font/google";
import "./globals.css";

const sans = DynaPuff({
  variable: "--font-sans",
  subsets: ["latin"],
});

const mono = Funnel_Sans({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sans.variable} ${mono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
